# Generated by Django 5.0.7 on 2024-10-23 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='नाम')),
                ('guru_father_husband', models.CharField(max_length=200, verbose_name='गुरु/पिता/पति')),
                ('address', models.TextField(verbose_name='पता')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='मोबाइल नंबर')),
                ('aadhaar_number', models.CharField(max_length=12, verbose_name='आधार नंबर')),
                ('position', models.CharField(max_length=100, verbose_name='पद')),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/', verbose_name='प्रोफाइल पिक्चर')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='पंजीकरण दिनांक')),
                ('letter_number', models.CharField(max_length=50, unique=True, verbose_name='पत्र क्रमांक')),
            ],
            options={
                'verbose_name': 'नियुक्ति पत्र',
                'verbose_name_plural': 'नियुक्ति पत्र',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('password', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_link', models.URLField()),
                ('testimonial_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
