# Generated by Django 5.0.7 on 2024-10-25 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_donation_delete_donationtransaction_delete_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='नाम')),
                ('guardian', models.CharField(max_length=200, verbose_name='गुरु/पिता/पति')),
                ('area', models.CharField(max_length=500, verbose_name='पता')),
                ('workarea', models.CharField(max_length=500, verbose_name='कार्य क्षेत्र')),
                ('field', models.CharField(max_length=200, verbose_name='विशेष क्षेत्र')),
                ('welfare_activity', models.TextField(verbose_name='कल्याण कार्य विवरण')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='मोबाइल नंबर')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='पंजीकरण दिनांक')),
                ('letter_number', models.CharField(max_length=50, unique=True, verbose_name='पत्र क्रमांक')),
            ],
            options={
                'verbose_name': 'सम्मान पत्र',
                'verbose_name_plural': 'सम्मान पत्र',
            },
        ),
    ]
